### ISSUE TITLE
Runtime error while starting connector

### ISSUE THREAD

**Issue by kirito73** [scylladb/scylla-cdc-source-connector#10]
Stack trace:

Caused by: java.lang.NoSuchMethodError: 'org.apache.kafka.connect.source.SourceConnectorContext com.scylladb.cdc.debezium.connector.ScyllaConnector.context()'
         at com.scylladb.cdc.debezium.connector.ScyllaConnector.buildMaster(ScyllaConnector.java:67)
         at com.scylladb.cdc.debezium.connector.ScyllaConnector.validate(ScyllaConnector.java:138)
         at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:318)
         at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:672)
         at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:669)
         at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:299)
         at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:248)

**Comment by ctuluctulu** [comment]
Hi. What did you do to avoid this error?

**Comment by kirito73** [comment]
Which version of Kafka are you using? This is compatible with Kafka 2.6.0+
I upgraded my Kafka version and it worked.

**Comment by kirito73** [comment]
> Hi. What did you do to avoid this error?

Which version of Kafka are you using? This is compatible with Kafka 2.6.0+
I upgraded my Kafka version and it worked.

**Comment by ctuluctulu** [comment]
I use 2.4.1. Thanks. I will upgrade my Kafka.

**Comment by ctuluctulu** [comment]
It works in 2.8!  Thank you!

**Comment by avelanarius** [comment]
Yes, Kafka 2.6.0+ is required for Scylla CDC Source Connector, as only those Kafka versions support `SourceConnector::context()` method we use to read the offsets on startup.
